#!/bin/zsh

# Install zplug if it doesn't exist
if [ ! -d "$HOME/.zplug" ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi

# Plugins
source ~/.zplug/init.zsh

# My zsh dotfiles
if grep -q "Arch Linux" /etc/*release; then
  zplug "soleblaze/dotfiles", use:"zsh/{*.zsh,os/archlinux.zsh}"
elif grep -q "Ubuntu" /etc/*release; then
  zplug "soleblaze/dotfiles", use:"zsh/{*.zsh,os/ubuntu.zsh}"
fi

# Other zsh plugins
zplug "MichaelAquilina/zsh-you-should-use"
zplug "Tarrasch/zsh-bd"
zplug "caarlos0/zsh-git-sync"
zplug "changyuheng/fz", defer:1
zplug "hlissner/zsh-autopair", defer:2
zplug "oz/safe-paste"
zplug "paulirish/git-open", as:plugin
zplug "rupa/z", use:z.sh
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search"
zplug 'wfxr/forgit', defer:1

# Competions
zplug 'g-plane/zsh-yarn-autocompletions'
zplug 'srijanshetty/zsh-pip-completion'
zplug 'zsh-users/zsh-completions'
zplug 's7anley/zsh-geeknote'

# Pure prompt fork by intelfx
zplug mafredri/zsh-async, from:github
zplug sinetoami/purien, use:purien.zsh, from:github, as:theme

# Install additional apps
zplug 'BurntSushi/ripgrep', \
    from:gh-r, \
    as:command, \
    rename-to:"rg"
zplug 'stedolan/jq', \
    from:gh-r, \
    as:command
zplug 'junegunn/fzf-bin', \
    as:command, \
    from:gh-r, \
    rename-to:"fzf"
zplug "k4rthik/git-cal", as:command
zplug "zdharma/zsh-diff-so-fancy", as:command, use:"bin/{git-dsf,diff-so-fancy}"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# Source local zshrc if it exists
if [ -f "$HOME/.zshrc_local" ]; then
  source "$HOME/.zshrc_local"
fi
